# Generated by Django 6.0.7 on 2026-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_mk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_sq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_en',
            field=models.TextField(blank=True, help_text='Comma-separated or free text', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_mk',
            field=models.TextField(blank=True, help_text='Comma-separated or free text', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_sq',
            field=models.TextField(blank=True, help_text='Comma-separated or free text', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_mk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_sq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
