# Generated by Django 6.0.7 on 2026-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('hero_tagline', models.CharField(blank=True, max_length=300)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('about_us_text', models.TextField(blank=True, help_text='Rich text HTML from the admin WYSIWYG editor')),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=300)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='e.g. {"instagram": "https://...", "facebook": "https://..."}')),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
