# Generated by Django 6.0.7 on 2026-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_text_en',
            field=models.TextField(blank=True, help_text='Rich text HTML from the admin WYSIWYG editor', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_text_mk',
            field=models.TextField(blank=True, help_text='Rich text HTML from the admin WYSIWYG editor', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_text_sq',
            field=models.TextField(blank=True, help_text='Rich text HTML from the admin WYSIWYG editor', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_mk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_sq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_mk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_sq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tagline_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tagline_mk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_tagline_sq',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
