# Generated by Django 6.0.7 on 2026-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address_mk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='address_sq',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
